AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to deploy CodeBuild

Resources:
  #Deployment
  CodeBuildDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                  - lambda:*
                  - logs:*
                  - ec2:*
                  - codeconnections:*
                  - ssm:*
                  - kms:*
                  - secretsmanager:*
                  - cloudformation:*
                  - iam:*
                  - apigateway:*
                Resource: "*"
          PolicyName: CodeBuildDeployPolicy

  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-deploy
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildDeployRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-deployment.yml
      

  #Migration
  CodeBuildMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
        
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                  - lambda:*
                  - logs:*
                  - ec2:*
                  - rds:*
                  - codeconnections:*
                  - ssm:*
                  - kms:*
                  - secretsmanager:*
                Resource: "*"
          PolicyName: CodeBuildMigrationPolicy

  CodeBuildMigrationProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-migration
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: CONNECTION_STRING
            Value: demo-project/connection-string
            Type: SECRETS_MANAGER
      ServiceRole: !GetAtt CodeBuildMigrationRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-migration.yml
      VpcConfig:
        VpcId: vpc-0cdb9341e56401645
        Subnets:
          - subnet-0ba92b13c578ff7dc
          - subnet-0d1cbb6674856b351
        SecurityGroupIds:
          - sg-0fae0b4067744f26a

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:  
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
          PolicyName: CodePipelinePolicy

  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Name: GitHub
              Configuration:
                ConnectionArn: arn:aws:codeconnections:ap-south-1:292578125952:connection/b317277a-0fbe-4331-827e-f33e3917a3ff
                FullRepositoryId: https://github.com/Hasil-21/Dummy-Files-Hasil.git
                BranchName: main
          Name: Source 

        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Name: DB
              Configuration:
                ProjectName: demo-project-migration
              InputArtifacts:
                - Name: SourceOutput
          Name: DatabaseMigration   

        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Name: API
              Configuration:
                ProjectName: demo-project-deploy
              InputArtifacts:
                - Name: SourceOutput
          Name: LambdaDeploy